baseURL = 'https://jessedp.github.io/hpcia-newsletter-archive/'
languageCode = 'en-us'
title = 'HPCIA Newsletter Archive'
theme = 'ink-free'


[params]
    toc = "floating"
    avatar = "/hpcia-newsletter-archive/HomePark_Horz_v1_rgb.png"
    favicon = "/hpcia-newsletter-archive/favicon.ico"
	subtitle = "Assorted HPCIA Newsletters from 1986 - 1991"

    featherIconsCDN = false

	# Site color - dark/light/auto
	mode = "light"

    # Max tags
	maxTags = 7

    # Define words per minute to approximate reading time
	wpm = 250

